"""drop excl

Revision ID: 8e55e1df7106
Revises: 0b519bb9e071
Create Date: 2023-03-06 08:54:41.481742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e55e1df7106'
down_revision = '0b519bb9e071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excl')
    sa.Enum(name='exclfamily').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excl',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('family', postgresql.ENUM('network', 'regex', name='exclfamily'), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='excl_pkey')
    )
    # ### end Alembic commands ###
