"""versioninfo service constraints

Revision ID: ab03e37b4677
Revises: 0b2d30fc1646
Create Date: 2023-10-11 11:11:37.577815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab03e37b4677'
down_revision = '0b2d30fc1646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version_info_temp', 'service_proto',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('version_info_temp', 'service_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version_info_temp', 'service_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('version_info_temp', 'service_proto',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
